version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_net

  minio:
    image: minio/minio:latest
    container_name: chat_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Aa@123456
      MINIO_PROMETHEUS_AUTH_TYPE: public
    labels:
      - "prometheus.enable=true"
      - "prometheus.job=minio"
      - "prometheus.port=9000"
      - "prometheus.path=/minio/v2/metrics/cluster"

    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - shared_net
    
  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    network_mode: "host"
    volumes:
      - ./coturn.conf:/etc/turnserver.conf
    restart: always
    command: turnserver --stun-only --no-tls --no-dtls --listening-port=3478

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: chat_mattermost
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=https://mattermost.manafintech.com
      - MM_FILESETTINGS_MAXFILESIZE=1073741824
      - MM_FILESETTINGS_DRIVERNAME=amazons3
      - MM_FILESETTINGS_AMAZONS3ACCESSKEYID=admin
      - MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY=Aa@123456
      - MM_FILESETTINGS_AMAZONS3BUCKET=mana
      - MM_FILESETTINGS_AMAZONS3ENDPOINT=minio:9000
      - MM_FILESETTINGS_AMAZONS3SSL=false
      - MM_FILESETTINGS_AMAZONS3SIGNV2=false
      - MM_PLUGINSETTINGS_ENABLEUPLOADS=true
    ports:
      - "127.0.0.1:8065:8065"
      - "8443:8443/udp"
      - "8443:8443/tcp"
    volumes:
      - mattermost_config:/mattermost/config
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_plugins:/mattermost/plugins
    networks:
      - shared_net

networks:
  shared_net:
    external: true
    name: my-shared-network

volumes:
  postgres_data:
  minio_data:
  mattermost_config:
  mattermost_data:
  mattermost_logs:
  mattermost_plugins:
